rules:
  - matches:
      dependencyNames:
        - ahmetb/kubectx
        - derailed/k9s
        - docker/buildx
        - docker/cli
        - docker/compose
        - kubernetes/kubernetes
    dependencyConfig:
      extractVersion: v(.*)
  - matches:
      dependencyNames:
        - kubernetes-sigs/kustomize
    dependencyConfig:
      extractVersion: (?:kustomize/)?v(.*)
